plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'bin/setup'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 45

Metrics/MethodLength:
  Max: 45

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ParameterLists:
  Max: 6

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Lint/SuppressedException:
  Enabled: false

Lint/UselessConstantScoping:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleLength:
  Max: 35

RSpec/MultipleExpectations:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 8
